name: pre-commit-shfmt CI

on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dev tools
        run: pip install -r requirements-dev.txt

      - name: Lint
        run: |
          pre-commit run -a
          nox -s lint

      - name: Build
        run: python3 -m build

      - name: Test
        run: nox -s test
